import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import {ModalInvest} from "../components/ModalInvest";
import {useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [showModal, setShowModal] = useState(false);
    const [projectId, setProjectId] = useState(0);
  return (
    <>
      <Head>
        <title>NULS ECOSYSTEM IGNITION INITIATIVE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
              <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                  <link
                      href="https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400..700;1,400..700&display=swap"
                      rel="stylesheet"/>
      </Head>
      <main className={styles.main} style={{backgroundImage: "linear-gradient(180deg,#0c111c,#0f1421 14.87%,#10131a 29.77%,#19191b 50%)"}}>
       <div>
           <div style={{textAlign:"center"}}>
               <Image src={"/neii.png"} alt={""} width={100} height={100} style={{borderRadius:"50%"}}/>
           </div>
           <div style={{fontSize:"50px", color:"white", marginTop:"20px", textAlign:"center"}}>
               NULS ECOSYSTEM IGNITION INITIATIVE
           </div>
           <div style={{padding:"45px", textAlign:"center"}}>
               <Link href="https://docs.google.com/document/d/19rbXoD9onFbnvLUCfynYRmlWj-z7Dp9fK-ZcIR6_gPc/edit?usp=sharing" target="_blank">
                   <button style={{padding:"10px", cursor:"pointer", border:"0px", color:"white", backgroundColor:"rgb(50, 224, 141)", borderRadius:"4px"}}>Know More About Us</button>

               </Link>
             </div>
           <div style={{backgroundColor:"rgba(114, 117, 126, 0.1)", color:"white", width:"100%", minWidth:"300px", borderRadius:"10px", padding:"10px 20px"}}>
                <div className={styles.listProject}>
                    <div>
                        Project
                    </div>
                    <div>
                        MAX ROI
                    </div>
                    <div>
                        Current ROI
                    </div>
                    <div>
                        STATUS
                    </div>
                </div>
               <hr/>
               <div className={styles.listProject}>
                   <div>
                       NULS Oracles
                   </div>
                   <div>
                       25x
                   </div>
                   <div>
                       12x
                   </div>
                   <div>
                       <div style={{display:"flex", alignItems:"center", justifyContent:"center"}}>
                           <div>
                               <button onClick={() => { setShowModal(true); setProjectId(1);}} style={{padding:"10px", cursor:"pointer", border:"0px", color:"white", backgroundColor:"rgb(50, 224, 141)", borderRadius:"4px"}}>Invest</button>
                           </div>
                           <div style={{padding:"0px 5px"}}>
                               <div style={{width:"80px", height:"20px", backgroundColor:"white", minHeight:"32px", borderRadius:"4px"}}><div style={{height:"100%",  borderRadius:"4px", width:"20%", backgroundColor:"rgb(50, 224, 141)"}}></div></div>
                           </div>
                           <div>
                               20%
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>

      </main>
          <ModalInvest display={showModal} displayToggle={setShowModal} project={projectId}/>
    </>
  )
}
